### ISSUE TITLE
Baking views doesn't generate Bootstrap html

### ISSUE THREAD

**Issue by aceat64** [elboletaire/twbs-cake-plugin#3]
I'm running CakePHP 3.0rc1, I had to modify the command to say "--theme" instead of "--template".

Example:

    bin/cake bake view tasks --theme Bootstrap

The resulting files are identical to the standard bake output.

**Comment by elboletaire** [comment]
I'm not really sure but, since CakePHP developers split bake actions into a separate plugin, I think it's not currently possible to bake using external templates.

At least, this is what I'm understanding in this issue: https://github.com/cakephp/bake/issues/2#issue-51803042 when they say "Allow baking anything".

I'll try to take a further look into it during these days..

Anyway, thanks for your report :smile:.

**Comment by elboletaire** [comment]
Nevermind! I was wrong.

I've updated bake templates to fit the new plugin requirements and now everything works nice :smiley:
